{
    "error": {
        "http_code": 404,
        "message": "Cannot find S3 cluster for storage cluster",
        "traceback": [
            "Traceback (most recent call last):\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/decorators.py\", line 28, in wrapper\n    return func(*args, **kwargs)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/presentation/s3/s3.py\", line 226, in get\n    'n_users': create_s3_users_service(logger).get_users_count(cluster_id),\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/users/services.py\", line 80, in get_users_count\n    return S3UserFinder(logger).count(cluster_id)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/users/users.py\", line 202, in count\n    data = self._user_gateway.count(cluster_id)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/users/users.py\", line 77, in count\n    return self._request(cluster_id, query)\n",
            "  File \"/usr/libexec/vstorage-ui-backend/venv/lib64/python3.4/site-packages/vstorage_ui_backend-1.3.185-py3.4.egg/backend/business/models/s3/users/users.py\", line 21, in _request\n    raise ObjectDoesNotExist('Cannot find S3 cluster for storage cluster')\n",
            "backend.business.models.exceptions.ObjectDoesNotExist: Cannot find S3 cluster for storage cluster\n"
        ],
        "subsytem": "presentation",
        "errors": null
    },
    "message": "Cannot find S3 cluster for storage cluster (Deprecated field)"
}